import { createRouter, createWebHashHistory, RouteRecordRaw } from 'vue-router'

export const routes: RouteRecordRaw[] = [
  {
    path: '/',
    name: 'Layout',
    component: () => import('@/views/home/index.vue'),
    redirect: '/home',
    children: [
      {
        path: '/home',
        name: 'Home',
        component: () => import('@/views/home/index.vue'),
        meta: {
          title: '首页',
          keepAlive: true,
          icon: 'House',
          hidden: false,
          affix: true,
          breadcrumb: false,
          activeMenu: '/home',
        },
      },
    ],
    meta: {
      title: '',
      keepAlive: true,
      icon: '',
      hidden: false,
      affix: true,
      breadcrumb: false,
      activeMenu: '/home',
    },
  },
  {
    path: '/screen',
    name: 'Screen',
    component: () => import('@/views/screen/index.vue'),
    meta: {
      title: '数据大屏',
      keepAlive: true,
      icon: 'PieChart',
      hidden: false,
      affix: true,
      breadcrumb: false,
      activeMenu: '/login',
    },
  },
  {
    path: '/bankCard',
    name: 'BankCard',
    component: () => import('@/views/bankCard/index.vue'),
    meta: {
      title: '银行卡管理',
      keepAlive: true,
      icon: 'CreditCard',
      hidden: false,
      affix: true,
      breadcrumb: false,
      activeMenu: '/login',
    },
  },
  {
    path: '/bookmark',
    name: 'Bookmark',
    component: () => import('@/views/bookmark/index.vue'),
    meta: {
      title: '书签管理',
      keepAlive: true,
      icon: 'Memo',
      hidden: false,
      affix: true,
      breadcrumb: false,
      activeMenu: '/login',
    },
  },
  {
    path: '/spider',
    name: 'Spider',
    component: () => import('@/views/bookmark/index.vue'),
    meta: {
      title: '爬虫管理',
      keepAlive: true,
      icon: 'Box',
      hidden: false,
      affix: true,
      breadcrumb: false,
      activeMenu: '/login',
    },
  },
  {
    path: '/jobs',
    name: 'Jobs',
    component: () => import('@/views/bookmark/index.vue'),
    meta: {
      title: '任务管理',
      keepAlive: true,
      icon: 'Timer',
      hidden: false,
      affix: true,
      breadcrumb: false,
      activeMenu: '/login',
    },
  },
  {
    path: '/menuMange',
    name: 'MenuMange',
    // component: () => import('@/layout/index.vue'),
    children: [
      {
        path: '/userMange',
        name: 'UserMange',
        component: () => import('@/views/menus/user/index.vue'),
        meta: {
          title: '用户管理',
          keepAlive: true,
          icon: 'User',
          hidden: false,
          affix: true,
          breadcrumb: false,
          activeMenu: '/home',
        },
      },
      {
        path: '/roleMange',
        name: 'RoleMange',
        component: () => import('@/views/menus/role/index.vue'),
        meta: {
          title: '角色管理',
          keepAlive: true,
          icon: 'Avatar',
          hidden: false,
          affix: true,
          breadcrumb: false,
          activeMenu: '/menus',
        },
      },
      {
        path: '/privilegeMange',
        name: 'PrivilegeMange',
        component: () => import('@/views/menus/privi/index.vue'),
        meta: {
          title: '权限管理',
          keepAlive: true,
          icon: 'Lock',
          hidden: false,
          affix: true,
          breadcrumb: false,
          activeMenu: '/home',
        },
      },
      {
        path: '/systemLog',
        name: 'SystemLog',
        component: () => import('@/views/menus/syslog/index.vue'),
        meta: {
          title: '系统日志',
          keepAlive: true,
          icon: 'Monitor',
          hidden: false,
          affix: true,
          breadcrumb: false,
          activeMenu: '/home',
        },
      },
      {
        path: '/configMange',
        name: 'ConfigMange',
        component: () => import('@/views/menus/config/index.vue'),
        meta: {
          title: '配置管理',
          keepAlive: true,
          icon: 'Setting',
          hidden: false,
          affix: true,
          breadcrumb: false,
          activeMenu: '/home',
        },
      },
    ],
    meta: {
      title: '菜单管理',
      keepAlive: true,
      icon: 'Menu',
      hidden: false,
      affix: true,
      breadcrumb: false,
      activeMenu: '/home',
    },
  },
  {
    path: '/login',
    name: 'Login',
    component: () => import('@/views/login/index.vue'),
    meta: {
      title: '登录',
      keepAlive: true,
      icon: 'el-icon-s-home',
      hidden: true,
      affix: true,
      breadcrumb: false,
      activeMenu: '/login',
    },
  },
  {
    path: '/about',
    name: 'About',
    component: () => import('@/views/about/index.vue'),
    meta: {
      title: '关于',
      keepAlive: true,
      icon: 'Reading',
      hidden: false,
      affix: true,
      breadcrumb: false,
      activeMenu: '/about',
    },
  },
  {
    path: '/404',
    name: '404',
    component: () => import('@/views/404/index.vue'),
    meta: {
      title: '404',
      keepAlive: true,
      icon: 'el-icon-s-home',
      hidden: true,
      affix: true,
      breadcrumb: false,
      activeMenu: '/404',
    },
  },
]

const router = createRouter({
  history: createWebHashHistory(),
  routes,
  scrollBehavior: () => ({ left: 0, top: 0 }),
})

export default router
